typography_spectrum: 0.19890745938755572
color:
  brandStrength: 0.2572981708217412
  lightness: 0.06015636376105249
  saturation: 0.5779325189068913
  rhythmicContrast: 0.03379766154102981
  brandColors:
    - '#E7E7E7'
    - '#94DBD3'
    - '#41B8BC'
    - '#C4903D'
    - '#E1AE5B'
layout_spectrum: 0.43860697210766375
author:
  name: Patrick Betters
  email: ''
  url: ''
name: The Golden Children
navigation:
  - name: Patrick Betters
    id: 3166d790-6296-4047-a004-da198e3d452a
    type: content
  - name: Facebook
    url: 'https://www.facebook.com/patrickbetters'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/patrickbetters/'
    type: external
  - name: Twitter
    url: 'https://twitter.com/PatrickBetters'
    type: external
title: Childhood Cancer Community Created by Patrick Betters
description: Childhood Cancer Community Created by Patrick Betters
