typography_spectrum: 0.5669171989429742
color:
  brandStrength: 0.4195492572616786
  lightness: 0.4694805054459721
  saturation: 0.6083710060920566
  rhythmicContrast: 0.002756768139079213
  brandColors:
    - '#C4D0DC'
    - '#EBC982'
    - '#708DB5'
    - '#FEFEFE'
    - '#E1EBF5'
layout_spectrum: 0.5790137641597539
author:
  name: Patrick Betters
  email: ''
  url: ''
name: The Golden Children
navigation:
  - name: Patrick Betters
    id: 3166d790-6296-4047-a004-da198e3d452a
    type: content
title: The Golden Children
description: Childhood Cancer Community Created by Patrick Betters
