typography_spectrum: 0.020477144746109843
color:
  brandStrength: 0.0647648002486676
  lightness: 0.5978007614612579
  saturation: 0.23604834149591625
  rhythmicContrast: 0.9333600522950292
  brandColors:
    - '#C4D0DC'
    - '#EBC982'
    - '#708DB5'
    - '#FEFEFE'
    - '#E1EBF5'
layout_spectrum: 0.43860697210766375
author:
  name: Patrick Betters
  email: ''
  url: ''
name: The Golden Children
navigation:
  - name: Patrick Betters
    id: 3166d790-6296-4047-a004-da198e3d452a
    type: content
  - name: Facebook
    url: 'https://www.facebook.com/patrickbetters'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/patrickbetters/'
    type: external
title: Childhood Cancer Community Created by Patrick Betters
description: Childhood Cancer Community Created by Patrick Betters
