typography_spectrum: 0.35805003601126373
color:
  brandStrength: 0.7573848764877766
  lightness: 0.5365422866307199
  saturation: 0.8359929090365767
  rhythmicContrast: 0.9260788923129439
  brandColors:
    - '#E7E7E7'
    - '#94DBD3'
    - '#41B8BC'
    - '#C4903D'
    - '#E1AE5B'
layout_spectrum: 0.7655187046620995
author:
  name: Patrick Betters
  email: ''
  url: ''
name: The Golden Children
navigation:
  - name: Patrick Betters
    id: 3166d790-6296-4047-a004-da198e3d452a
    type: content
title: Childhood Cancer Community Created by Patrick Betters
description: Childhood Cancer Community Created by Patrick Betters
