typography_spectrum: 0.3098366598132998
color:
  brandStrength: 0.24636514950543642
  lightness: 0.8325207952875644
  saturation: 0.39492728165350854
  rhythmicContrast: 0.5053816058207303
  brandColors:
    - '#E7E7E7'
    - '#94DBD3'
    - '#41B8BC'
    - '#C4903D'
    - '#E1AE5B'
layout_spectrum: 0.06052754237316549
author:
  name: Patrick Betters
  email: ''
  url: ''
name: The Golden Children
navigation:
  - name: Patrick Betters
    id: 3166d790-6296-4047-a004-da198e3d452a
    type: content
title: The Golden Children
description: Childhood Cancer Community Created by Patrick Betters
