typography_spectrum: 0.45490571251139045
color:
  brandStrength: 0.918824459426105
  lightness: 0.5082019267138094
  saturation: 0.9900548821315169
  rhythmicContrast: 0.7642044597305357
  brandColors:
    - '#C4D0DC'
    - '#EBC982'
    - '#708DB5'
    - '#FEFEFE'
    - '#E1EBF5'
layout_spectrum: 0.5874819753225893
author:
  name: Patrick Betters
  email: ''
  url: ''
name: The Golden Children
navigation:
  - name: Patrick Betters
    id: 3166d790-6296-4047-a004-da198e3d452a
    type: content
title: The Golden Children
description: Childhood Cancer Community Created by Patrick Betters
