typography_spectrum: 0.42177418735809624
color:
  brandStrength: 0.7573848764877766
  lightness: 0.5365422866307199
  saturation: 0.8359929090365767
  rhythmicContrast: 0.9260788923129439
  brandColors:
    - '#E7E7E7'
    - '#94DBD3'
    - '#41B8BC'
    - '#C4903D'
    - '#E1AE5B'
layout_spectrum: 0.11689165839925408
author:
  name: Patrick Betters
  email: ''
  url: ''
name: The Golden Children
title: Childhood Cancer Community Created by Patrick Betters
description: Childhood Cancer Community Created by Patrick Betters
